### PR TITLE
Search Card & Search Tags

### PR DESCRIPTION
**Pull request by itsninaricci29**
Screen Shot 2020-03-11 at 9 43 17 AM

### CODE REVIEW

**Comment by VeerpalBrar** [comment]
What is the purpose of the Save drop down?

**Comment by itsninaricci29** [comment]
> What is the purpose of the Save drop down?

If the user wants to go back to it later. Like the save feature on instagram or pin

**Comment by VeerpalBrar** [comment]
Okay, I don't think we have time to implement that feature by the end of the month. You can create a issue with the enhancement tag for implementing this later on. I think for right now, it's a bit out of scope.

**Comment by itsninaricci29** [comment]
> Okay, I don't think we have time to implement that feature by the end of the month. You can create a issue with the enhancement tag for implementing this later on. I think for right now, it's a bit out of scope.

For sure! Ill comment it out for now. Is that ok?

**Comment by itsninaricci29** [comment]
Screen Shot 2020-03-11 at 2 50 58 PM

**Pull request merged**
